#!/usr/bin/bash
set -euo pipefail

readonly overlay_state=/run/fuse-overlayfs
readonly overlay_lower=$overlay_state/lower
readonly overlay_root=/run/root

printf 'init: preparing overlay layers\n'
mount -t tmpfs -o mode=0700,nosuid,nodev tmpfs /run
mount -t proc -o nosuid,nodev,noexec proc /proc
mkdir -p "$overlay_lower" "$overlay_state/upper" "$overlay_state/work" "$overlay_root"
mount --bind / "$overlay_lower"

printf 'init: starting fuse-overlayfs\n'
fuse-overlayfs \
    -o "lowerdir=$overlay_lower,upperdir=$overlay_state/upper,workdir=$overlay_state/work" \
    "$overlay_root"

mount --move /dev "$overlay_root/dev"
exec chroot "$overlay_root" /usr/lib/sima/sima-init

#printf 'init: mounting runtime filesystems\n'
#mkdir -p "$overlay_root"/{dev,proc,sys,run}
#mount -t proc -o nosuid,nodev,noexec proc "$overlay_root/proc"
#mount -t sysfs -o nosuid,nodev,noexec sysfs "$overlay_root/sys"
#mount -t tmpfs -o mode=0755,nosuid,nodev tmpfs "$overlay_root/run"
#
#printf 'init: starting device manager\n'
#chroot "$overlay_root" /usr/lib/systemd/systemd-udevd --resolve-names=never &
#while [[ ! -S "$overlay_root/run/udev/control" ]]; do :; done
#chroot "$overlay_root" /usr/bin/udevadm trigger --verbose --action=add --subsystem-match=net --settle --wait-daemon=10
#
#printf 'init: starting network service\n'
#install -d -m 0755 "$overlay_root/run/dbus"
#chroot "$overlay_root" /usr/bin/dbus-daemon --system --fork --nopidfile
#chroot "$overlay_root" /usr/bin/NetworkManager --no-daemon \
#>"$overlay_root/run/NetworkManager.log" 2>&1 &
#
#printf 'init: mounted fuse-overlayfs root\n'
#exec chroot "$overlay_root" /usr/bin/bash
