timeout: 0

/CoolPotOS
    protocol: limine
    path: $boot():/boot/kernel.elf.gz
    cmdline: console=@CONSOLE@ rootfs=rootfs-x86_64.erofs rdinit=/init
    module_path: boot():/boot/rootfs-x86_64.erofs
    module_string: rootfs-x86_64.erofs
