timeout: 0

/CoolPotOS
    protocol: limine
    kernel_path: boot():/kernel.elf
    cmdline: console=fb0 initrd=alpine-initramfs-x86_64 rdinit=/usr/bin/sh
    module_path: boot():/boot/alpine-initramfs-x86_64
    module_string: alpine-initramfs-x86_64
