timeout: 0

/CoolPotOS
    protocol: limine
    kernel_path: boot():/kernel.elf
    cmdline: console=fb0 rootfs=cachyos-rootfs-x86_64.erofs rdinit=/usr/bin/bash
    module_path: boot():/boot/cachyos-rootfs-x86_64.erofs
    module_string: cachyos-rootfs-x86_64.erofs
